# Jekyll configuration file

# Site settings
title: Curtin Robotics Club
email: curtinroboticsclub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://curtinrobotics.github.io" # the base hostname & protocol for your site
github_username: curtinrobotics
github_repository: curtinrobotics.github.io

# Build settings
markdown: kramdown

# Don't include readme and license files
exclude: [README.md, LICENSE.md]
