# Jekyll configuration file

# Site settings
title: Curtin Robotics Club
acronym: CRoC
email: curtinroboticsclub@gmail.com
description: >
  Curtin University Robotics Club. A member run guild club concerned with building robots.
url: "http://curtinrobotics.github.io" # the base hostname & protocol for your site
github_username: curtinrobotics
github_repository: curtinrobotics.github.io

# Build settings
markdown: kramdown

# Don't include readme and license files
exclude: [README.md, LICENSE.md]
